//Flower maker

Flower myRose = new Flower(40, 'Rose');
System.debug('🌹 My flower is a ' + myRose.variety + ' with ' + myRose.petalCount + ' petals.');

myRose.wilt();
System.debug('🌹 After wilting, my flower is a ' + myRose.variety + ' with ' + myRose.petalCount + ' petals.');

Flower myTulip = new Flower(6, 'Tulip');
System.debug('🌷 My flower is a ' + myTulip.variety + ' with ' + myTulip.petalCount + ' petals.');
myTulip.wilt();
System.debug('🌷 After wilting, my flower is a ' + myTulip.variety + ' with ' + myTulip.petalCount + ' petals.');

Flower myDaisy = new Flower(20, 'Daisy');
System.debug('🌼 My flower is a ' + myDaisy.variety + ' with ' + myDaisy.petalCount + ' petals.');
myDaisy.wilt();
System.debug('🌼 After wilting, my flower is a ' + myDaisy.variety + ' with ' + myDaisy.petalCount + ' petals.');


System.debug('🌹 My flower is a ' + myRose.variety + ' with ' + myRose.petalCount + ' petals.');


